# Generated by Django 4.1.3 on 2022-11-19 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0003_alter_catchreceipt_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchreceipt',
            name='invoices_id',
            field=models.CharField(default='0', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='catchreceipt',
            name='accountant',
            field=models.CharField(help_text=' المحاسب ', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='catchreceipt',
            name='delegate',
            field=models.ForeignKey(help_text=' المندوب ', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
