# Generated by Django 4.1.3 on 2022-11-20 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_catchreceipt_invoices_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catchreceipt',
            name='invoices_id',
        ),
        migrations.RemoveField(
            model_name='invoices',
            name='CatchReceipt',
        ),
        migrations.AddField(
            model_name='catchreceipt',
            name='invoices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.invoices'),
        ),
    ]
