# Generated by Django 4.1.3 on 2022-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_remove_catchreceipt_invoices_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='auth',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
