# Generated by Django 4.1.3 on 2022-11-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_invoices_status_alter_invoices_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=225, null=True),
        ),
    ]
