# Generated by Django 4.1.3 on 2022-11-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_remove_invoices_auth_invoices_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoices',
            name='auth',
        ),
        migrations.AddField(
            model_name='invoices',
            name='auth',
            field=models.CharField(blank=True, default='active', max_length=225, null=True),
        ),
    ]
