# Generated by Django 4.1.2 on 2022-11-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_alter_drivermodel_vehicle_type'),
        ('financial', '0011_catchreceipt_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catchreceipt',
            name='amount',
            field=models.CharField(default='0', help_text=' الاجرة', max_length=225),
        ),
        migrations.AlterField(
            model_name='catchreceipt',
            name='deduction',
            field=models.CharField(default='0', help_text='خصم', max_length=225),
        ),
        migrations.AlterField(
            model_name='catchreceipt',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivermodel'),
        ),
        migrations.AlterField(
            model_name='catchreceipt',
            name='overnight',
            field=models.CharField(default='0', help_text=' المبات', max_length=225),
        ),
        migrations.AlterField(
            model_name='catchreceipt',
            name='return_fare',
            field=models.CharField(default='0', help_text=' اجرة رجعة', max_length=225),
        ),
    ]
