# Generated by Django 4.1.2 on 2022-10-26 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentmodel',
            name='company',
        ),
        migrations.AlterField(
            model_name='shipmentmodel',
            name='status',
            field=models.CharField(default='Shipping', help_text='حالة الشحنة', max_length=10),
        ),
        migrations.AddField(
            model_name='shipmentmodel',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.companymodel'),
        ),
    ]
