# Generated by Django 4.1.2 on 2022-10-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('driver_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('driver_name', models.CharField(help_text='اسم السائق', max_length=225)),
                ('driver_nationality', models.CharField(choices=[('Saudi', 'Saudi'), ('Yemeni', 'Yemeni'), ('Syrian', 'Syrian'), ('Egypt', 'Egypt'), ('Afghanistan', 'Afghanistan'), ('Pakistani', 'Pakistani'), ('Jordanian', 'Jordanian'), ('Indian', 'Indian'), ('other', 'other')], default='other', help_text='جنسية السائق', max_length=20)),
                ('driver_phone_number', models.CharField(help_text='رقم هاتف السائق ', max_length=16)),
                ('Identification_Number', models.CharField(help_text='رقم الهوية/الاقامة', max_length=10)),
                ('truck_plate_number', models.CharField(help_text='رقم لوحة الشاحنة', max_length=8)),
                ('Vehicle_Type', models.CharField(choices=[('Truck_Reefers', 'Truck_Reefers'), ('Truck_Flatbed', 'Truck_Flatbed'), ('Truck_high_sides', 'Truck_high_sides'), ('Truck_Curtainsider', 'Truck_Curtainsider'), ('lory_Flatbed', 'lory_Flatbed'), ('lory_Reefers', 'lory_Reefers'), ('dinah_Flatbed', 'dinah_Flatbed'), ('dinah_Reefers', 'dinah_Reefers')], default='Truck_Flatbed', help_text='نوع السيارة(سطحة - جوانب) ....', max_length=30)),
                ('Sequence_Number', models.CharField(help_text='الرقم التسلسلي من الاستمارة', max_length=30)),
                ('Owner_car_id_number', models.CharField(help_text='رقم هوية مالك السيارة', max_length=10)),
                ('Identification_photo', models.ImageField(help_text='صورة الهوية/الاقامة ', null=True, upload_to='driver/')),
            ],
        ),
    ]
