# Generated by Django 4.1.2 on 2022-11-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivermodel',
            name='Identification_photo',
        ),
    ]
