# Generated by Django 4.1.2 on 2022-11-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_remove_drivermodel_identification_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='Identification_Number',
            field=models.CharField(blank=True, help_text='رقم الهوية/الاقامة', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='Owner_car_id_number',
            field=models.CharField(blank=True, help_text='رقم هوية مالك السيارة', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='Sequence_Number',
            field=models.CharField(blank=True, help_text='الرقم التسلسلي من الاستمارة', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='Vehicle_Type',
            field=models.CharField(blank=True, choices=[('Truck_Reefers', 'Truck_Reefers'), ('Truck_Flatbed', 'Truck_Flatbed'), ('Truck_high_sides', 'Truck_high_sides'), ('Truck_Curtainsider', 'Truck_Curtainsider'), ('lory_Flatbed', 'lory_Flatbed'), ('lory_Reefers', 'lory_Reefers'), ('dinah_Flatbed', 'dinah_Flatbed'), ('dinah_Reefers', 'dinah_Reefers')], default='Truck_Flatbed', help_text='نوع السيارة(سطحة - جوانب) ....', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='driver_name',
            field=models.CharField(blank=True, help_text='اسم السائق', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='driver_nationality',
            field=models.CharField(blank=True, choices=[('Saudi', 'Saudi'), ('Yemeni', 'Yemeni'), ('Syrian', 'Syrian'), ('Egypt', 'Egypt'), ('Afghanistan', 'Afghanistan'), ('Pakistani', 'Pakistani'), ('Jordanian', 'Jordanian'), ('Indian', 'Indian'), ('other', 'other')], default='other', help_text='جنسية السائق', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='driver_phone_number',
            field=models.CharField(blank=True, help_text='رقم هاتف السائق ', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='truck_plate_number',
            field=models.CharField(blank=True, help_text='رقم لوحة الشاحنة', max_length=8, null=True),
        ),
    ]
